obj-$(CONFIG_VIDEO_MFC50) += s3c-mfc.o
obj-$(CONFIG_VIDEO_MFC50) += s3c_mfc_buffer_manager.o
obj-$(CONFIG_VIDEO_MFC50) += s3c_mfc_common.o
obj-$(CONFIG_VIDEO_MFC50) += s3c_mfc_intr.o
obj-$(CONFIG_VIDEO_MFC50) += s3c_mfc_memory.o
obj-$(CONFIG_VIDEO_MFC50) += s3c_mfc_opr.o

ifeq ($(CONFIG_VIDEO_MFC50_DEBUG),y)
EXTRA_CFLAGS += -DDEBUG
endif
