obj-$(CONFIG_VIDEO_FIMC)	+= fimc/
obj-$(CONFIG_VIDEO_JPEG)	+= jpeg/
obj-$(CONFIG_VIDEO_TV20)        += tv20/
obj-$(CONFIG_VIDEO_TV30)        += tv30/
obj-$(CONFIG_VIDEO_ROTATOR)    += rotator/
obj-$(CONFIG_VIDEO_MFC50)	+= mfc50/
obj-$(CONFIG_VIDEO_FIMG2D)	+= fimg2d/

EXTRA_CFLAGS += -Idrivers/media/video

